ci: run all cargo lint steps even on failure

diff --git a/.github/workflows/check-lint.yaml b/.github/workflows/check-lint.yaml
--- a/.github/workflows/check-lint.yaml
+++ b/.github/workflows/check-lint.yaml
@@ -157,12 +157,25 @@ jobs:
       - uses: metalbear-co/setup-protoc@770e54d44679c8e1d8fdc06d1d9268fa79fbefb4
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
-      - run: cargo clippy --all-targets --all-features --target ${{ matrix.target }} --keep-going --quiet -- "-Wclippy::indexing_slicing" -D warnings
-      - name: cargo fmt, operator crd check (run only on one platform)
+      - name: cargo clippy
+        id: cargo_clippy
+        continue-on-error: true
+        run: cargo clippy --all-targets --all-features --target ${{ matrix.target }} --keep-going --quiet -- "-Wclippy::indexing_slicing" -D warnings
+      - name: cargo fmt (run only on one platform)
+        id: cargo_fmt
         if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
+        continue-on-error: true
+        run: cargo fmt --all -- --check
+      - name: operator crd check (run only on one platform)
+        id: operator_crd_check
+        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
+        continue-on-error: true
+        run: cargo check -p mirrord-operator --features crd --target ${{ matrix.target }} --keep-going --quiet
+      - name: check all lint steps passed
+        if: ${{ !cancelled() && (steps.cargo_clippy.outcome == 'failure' || steps.cargo_fmt.outcome == 'failure' || steps.operator_crd_check.outcome == 'failure') }}
         run: |
-          cargo fmt --all -- --check
-          cargo check -p mirrord-operator --features crd --target ${{ matrix.target }} --keep-going --quiet
+          echo "One or more cargo lint checks failed."
+          exit 1
   shear:
     if: ${{ inputs.run_rust }}
     name: 'cargo shear'
