..

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -185,7 +185,7 @@ jobs:
     needs: [build_mirrord, test_agent_image]
     env:
       MIRRORD_AGENT_RUST_LOG: "warn,mirrord=debug"
-      SERVICE_PORT: "30000"
+      # SERVICE_PORT: "30000"
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
@@ -204,23 +204,24 @@ jobs:
       - uses: actions/setup-python@v3
       - run: pip3 install flask
       - name: setup cluster requirements
-        run: |
-          brew install kind
-          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
-          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
-          open -a /Applications/Docker.app --args --unattended --accept-license
-          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
-          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+        run: brew install docker colima kubectl
+        # run: |
+        #   brew install kind
+        #   HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+        #   sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+        #   open -a /Applications/Docker.app --args --unattended --accept-license
+        #   echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+        #   while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
       - name: create cluster
-        run: kind create cluster --config tests/kind.yaml
+        run: colima start --kubernetes --network-address
       - name: download image
         uses: actions/download-artifact@v2
         with:
           name: test
           path: /tmp
       - name: load image
-        run: kind load image-archive /tmp/test.tar
+        run: docker load --input /tmp/test.tar
       - name: cargo test
         run: cargo test -p tests
       - name: Collect container logs
