misc: remove mirrord/config/configuration.md and relevant CI steps

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -163,19 +163,19 @@ jobs:
         with:
           files: |
             mirrord-schema.json
-      - name: get configuration.md changes
-        id: changed-configuration-md
-        uses: metalbear-co/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
-        with:
-          files: |
-            mirrord/config/configuration.md
-      - name: verify configuration.md is up-to-date
-        run: |
-          if [ "${{ steps.changed-config-schema.outputs.any_changed }}" == "true" ] && [ "${{ steps.changed-configuration-md.outputs.any_changed }}" != "true" ]; then
-            echo "Error: mirrord configuration has changed but `configuration.md` documentation has not."
-            echo "Try running medschool (see `./medschool/readme.md`) and updating `configuration.md`."
-            exit 1
-          fi
+      # - name: get configuration.md changes
+      #   id: changed-configuration-md
+      #   uses: metalbear-co/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
+      #   with:
+      #     files: |
+      #       mirrord/config/configuration.md
+      # - name: verify configuration.md is up-to-date
+      #   run: |
+      #     if [ "${{ steps.changed-config-schema.outputs.any_changed }}" == "true" ] && [ "${{ steps.changed-configuration-md.outputs.any_changed }}" != "true" ]; then
+      #       echo "Error: mirrord configuration has changed but `configuration.md` documentation has not."
+      #       echo "Try running medschool (see `./medschool/readme.md`) and updating `configuration.md`."
+      #       exit 1
+      #     fi
       - name: output test
         run: |
           echo ${{ steps.changed-rs.outputs.any_changed }};
